# -*- coding: utf-8 -*-
"""ALGORITMA FUNGSI(BUKU DIWA)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WYeKejhM5qdmZEMGSYwHj4Htd_B5rlI7
"""

# membuat fungsi
def salam():
  print ("hello, ini Diwa")
# pemanggilan fungsi
salam()
salam()
salam()

def salam(ucapan):
  print(ucapan)
salam("anggun: waaaa,udah makan belom?")
salam("diwa: pake nanya!!!")
salam("anggun: mau di masakin ga?")
salam("diwa: boleh la adit nek kate e")
salam("adit: lah ku yang kene!!!")

def luas_segitiga(alas, tinggi):
  luas = (alas * tinggi) / 2
  print ("luas segitiga: %f" % luas)

luas_segitiga(5, 6)

# membuat variabel global
nama = "belajar kode"
versi = "1.0.0"

def help():
  # ini variabel lokal
  nama = "programku"
  versi = "1.0.1"
  # mengakses variabel lokal
def help():
  nama = "programku"
  versi = "1.0.1"
  print ("nama: %s" % nama)
  print ("nama: %s" % versi)

# mengakses varibel global
print ("nama: %s" % nama)
print ("nama: %s" % versi)

# memanggil fungsi help()
help()

# membuat variabel global
nama = "DIWA MULKI"
tgl_lhir = "12-09-2004"

def biodata():
  # ini variabel lokal
  hobi = "street basket"
  Jurusan = "ILKOM"
  tmpt_tinggal = "TEBRONG"
  # mengakses variabel lokal
  # ini variabel lokal
  print ("hobi: %s" % hobi)
  print ("Jurusan: %s" % Jurusan)
  print ("tmpt_tinggal: %s" % tmpt_tinggal)
# mengakses varibel global
print ("nama: %s" % nama)
print ("tgl_lhir: %s" % tgl_lhir)

# memanggil fungsi biodata()
biodata()

# fungsi untuk menampilkan semua data
def show():
  if len(buku) <= 0:
      print("BELUM ADA DATA")
  else:
      for indeks in range(len(buku)):
        print("[{}]] {}" .format(indeks, buku[indeks]))

def show():
  if len(buku) <= 0:
      print("BELUM ADA DATA")
  else:
      for indeks in range(len(buku)):
        print("[{}]] {}" .format(indeks, buku[indeks]))

def insert_data():
  buku_baru = input("judul buku: ")
  buku.append(buku_baru)

def edit_data():
  show_data()
  indeks = int(input("inputkan ID buku"))
  if indeks > len(buku):
    print("ID salah")
  else:
      judul_baru = input("judul baru: ")
      buku[indeks] = judul_baru

def delete_data():
  show_data()
  indeks = int(input("inputkan ID buku"))
  if indeks > len(buku):
    print("ID salah")
  else:
      buku.remove(buku[indeks])

def show_menu():
  print("\n")
  print("---------- MENU ----------")
  print("[1] show data")
  print("[2] insert data")
  print("[3] edit data")
  print("[4] delete data")
  print("[5] exit")

  menu = input("PILIH MENU> ")
  print("\n")

buku = []
def show_data():
     if len(buku) <= 0:
        print("BELUM ADA DATA")
     else:
         for indeks in range(len(buku)):
            print("[{}] {}".format(indeks, buku [indeks]))

def insert_data():
    buku_baru = input("judul buku: ")
    buku.append(buku_baru)

def edit_data():
    show_data
    indeks = int(input("inputkan ID buku: "))
    if indeks > len(buku):
      print("ID salah")
    else:
        judul_baru = input("Judul baru: ")
        buku[indeks] = judul_baru

def delete_data():
    show_data()
    indeks = int(input("inputkan ida buku"))
    if indeks > len(buku):
        print("id salah")
    else:
        buku.remove(buku[indeks])

def show_menu():
    print("\n")
    print("----------MENU----------")
    print("[1] show data")
    print("[2] insert data")
    print("[3] edit data")
    print("[4] delete data")
    print("[5] exit")

    menu = input("PILIH MENU")
    print("\n")

    if int(menu) == 1:
        show_data()
    elif int(menu) == 2:
        insert_data()
    elif int(menu) == 3:
        edit_data()
    elif int(menu) == 4:
        delete_data()
    elif int(menu) == 5:
        exit()
    else:
        print("salah pilih!")
if __name__ =="__main__":
      while True:
        show_menu()