# -*- coding: utf-8 -*-
"""ALGORITMA BUKU

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJkFdJrcT32y3XKwXdV_XHTeoHmyzz-G
"""

# membuat fungsi
def salam()
    print ("hello, selamat pagi")

## pemanggilan fungi
salam()

# membuat fungsi
def salam (ucapan):
    print (ucapan)
salam("selamat siang")

# Membuat fungsi dengan parameter
def luas_segitiga(alas, tinggi):
    luas = (alas * tinggi) / 2
    print ("luas segitiga: %f" % luas)

# pemanggilan fungsi
luas_segitiga(4, 6)

def luas_persegi(sisi):
    luas = sisi * sisi
    return luas

# pemanggilan fungsi
print ("luas persegi: %d" % luas_persegi(6))

# membuat variabel global
nama = "belajar kode"
versi = "1.0.0"

def help():
    # ini variabel lokal
    nama  = "programanku"
    versi = "1.0.1"
    # mengakses variabel lokal
    print ("nama: %s" % nama)
    print ("nama: %s" % versi)

# mengakses varibel global
print ("nama: %s" % nama)
print ("nama: %s" % versi)

# memanggil fungsi help()
help()

# membuat variabel global
nama = "Diwa Mulki"
tanggal_lahir = "12-09-2004"

def biodata():
  # ini variabel lokal
    hobi = "Bermain Basket"
    Jurusan = "ILKOM"
    tempat_tinggal = "Teberong"
    # mengakses variabel lokal
  print ("hobi: %S" % hobi)
  print ("Jurusan: %s" % Jurusan)
  print ("tempat_tinggal: %s" % tempat_tinggal)

# mengakses varibel global
print ("nama: %s" % nama)
print ("tanggal_lahir: %s" % tanggal_lahir)


# memanggil fungsi biodata()
biodata()

buku = []

 # fungsi untuk menampilkan semua data
def show_data():
     if len(buku) <= 0:
        print("BELUM ADA DATA")
     else:
         for indeks in range(len(buku)):
            print("[{}] {}".format(indeks, buku [indeks]))
# fungsi untuk menambah data
def insert_data():
    buku_baru = input("JUDUL BUKU: ")
    buku.append(buku_baru)
# fungsi untuk edit data
def edit_data():
    show_data
    indeks = int(input("inputkan ID buku: "))
    if indeks > len(buku):
      print("ID salah")
    else:
        judul_baru = input("Judul baru: ")
        buku[indeks] = judul_baru
# fungsi untuk delet data
def delete_data():
    show_data
    indeks = int(input("inputkan ID buku: "))
    if indeks > len(buku):
      print("ID salah")
    else:
        Buku.remove(buku[indeks])
# fungsi untuk menampilkan menu
def show_menu():
  print("\n")
  print("------------ MENU ----------")
  print("[1] Show Data")
  print("[2] Insert Data")
  print("[3] Edit Data")
  print("[4] Delete Data")
  print("[5]  Exit")

  menu = input ("PILIH MENU>")
  print("\n")

  if int(menu) == 1:
      show_data()
  elif int(menu) == 2:
      insert_data()
  elif int(menu) == 3:
      edit_data()
  elif int(menu) == 4:
      delete_data()
  elif int(menu) == 5:
      exit()
  else:
      print("salah pilih!")

if  __name__ == "__main__":

    while True:
        show_menu()

# fungsi untuk menampilkan menu
def show_menu():
  print("\n")
  print("------------ MENU ----------")
  print("[1] Show Data")
  print("[2] Insert Data")
  print("[3] Edit Data")
  print("[4] Delete Data")
  print("[5]  Exit")

  MENU = input ("PILIH MENU>")
  print("\n")