# -*- coding: utf-8 -*-
"""perulangan 1 diwa

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16r8V2wCp1wotfUpWN94N7qchvf2X2og7
"""

listkota = ['jakarta', 'surabaya', 'depok', 'bekasi', 'solo', 'jogjakarta', 'semarang', 'makasar'
]

for kota in listkota:
  print(kota)

listkota = ['jakarta', 'surabaya', 'depok', 'bekasi', 'solo', 'jogjakarta', 'semarang', 'makasar'
]

for i, kota in enumerate(listkota):
  print(i, kota)

## 0 sampai 4
for i in range(5):
  print("perulangan ke -", i)

## Bilangan genap kelipatan 2
for i in range(2,12,2):
  print('i =', i)

## Bilangan genap kelipatan 2
for bilangan_ganjil in range(1,12,2):
  print(bilangan_ganjil)

tuplebuah =('mangga', 'jeruk', 'apel', 'pepaya')

for buah in tuplebuah:
  print(buah)

for karakter in "indonesiaID":
 print(karakter)

for i in range(10, 20):
  # skip jika i == 15
  if (i == 15):
    continue
  print(i)

for i in range(10, 20):
  # hentikan jika i ==15
  if (i == 15):
    break
  print(i)

listkota = [
    'jakarta', 'surabaya', 'depok', 'bekasi', 'solo',
    'jogjakarta', 'semarang', 'makasar'
]

for kota in listkota:
  print(kota)
else:
  print('Tidak ada lagi item yang tersisa')

listkota = [
    'jakarta', 'surabaya', 'depok', 'bekasi', 'solo',
    'jogjakarta', 'semarang', 'makasar'
]

kotaYangDicari = input('ketika nama kota yang kamu cari: ')

for i, kopta in enumerate(listkota):
  # kita uba katanya ke lowercase agar
  # menjadi case insensitive
  if kota.lower() == kotaYangDicari.lower():
    print('kota yang anda cari berada pada indeks', i)
    break
else:
  print('kota yang anda cari berada pada indeks 4')